# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/bash

srcdir = .
top_srcdir = .

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/FishGUI
pkglibdir = $(libdir)/FishGUI
pkgincludedir = $(includedir)/FishGUI
top_builddir = .

ACLOCAL = ${SHELL} /home/ywwang/FishGUI/MVC_X11/missing --run aclocal
AUTOCONF = ${SHELL} /home/ywwang/FishGUI/MVC_X11/missing --run autoconf
AUTOMAKE = ${SHELL} /home/ywwang/FishGUI/MVC_X11/missing --run automake
AUTOHEADER = ${SHELL} /home/ywwang/FishGUI/MVC_X11/missing --run autoheader

INSTALL = ./install-sh -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
AMTAR = ${SHELL} /home/ywwang/FishGUI/MVC_X11/missing --run tar
AWK = gawk
CXX = g++
DEPDIR = .deps
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
OBJEXT = o
PACKAGE = FishGUI
VERSION = 1.0
X_CFLAGS =  -I/usr/openwin/include
X_EXTRA_LIBS = -lsocket  -lnsl
X_LIBS =  -L/usr/openwin/lib -R/usr/openwin/lib
X_PRE_LIBS =  -lSM -lICE
am__include = include
am__quote = 
install_sh = /home/ywwang/FishGUI/MVC_X11/install-sh

AUTOMAKE_OPTIONS = foreign

bin_PROGRAMS = FishGUI

FishGUI_SOURCES = ../Source/OSStartup/main.cpp                    \
                                                                  \
                  ../Source/MVC_Application/MyApp.cpp                 \
                  ../Source/MVC_Application/MainWindow.cpp            \
                  ../Source/MVC_Application/MyModel.cpp                  \
                  ../Source/MVC_Application/MyView.cpp                  \
                  ../Source/MVC_Application/Win1.cpp                  \
                                                                  \
                  ../Source/Framework/FG_Application.cpp          \
                  ../Source/Framework/FG_Object.cpp               \
                  ../Source/Framework/FG_Container.cpp            \
                  ../Source/Framework/FG_Window.cpp               \
                  ../Source/Framework/FG_Screen.cpp               \
                  ../Source/Framework/FG_Widget.cpp               \
                  ../Source/Framework/FG_TextWidget.cpp           \
                  ../Source/Framework/FG_Group.cpp                \
                  ../Source/Framework/FG_Bitmap.cpp               \
                  ../Source/Framework/FG_Button.cpp               \
                  ../Source/Framework/FG_Label.cpp                \
                  ../Source/Framework/FG_Edit.cpp                 \
                  ../Source/Framework/FG_CheckBox.cpp             \
                  ../Source/Framework/FG_RadioButton.cpp          \
                  ../Source/Framework/FG_TimerManager.cpp         \
                  ../Source/Framework/FG_KeyMap.cpp               \
                  ../Source/Framework/FG_MsgMap.cpp               \
                                                                  \
                  ../Source/OSAdaptor/FG_X11Adaptor.cpp           \
                  ../Source/OSAdaptor/FG_X11DrawInterface.cpp     \
                  ../Source/OSAdaptor/FG_OSAdaptor.cpp            \
                                                                  \
                  ../Source/Utility/FG_String.cpp                 \
                  ../Source/Utility/FG_Rect.cpp

subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES =
bin_PROGRAMS = FishGUI$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_FishGUI_OBJECTS = main.$(OBJEXT) MyApp.$(OBJEXT) MainWindow.$(OBJEXT) \
	MyModel.$(OBJEXT) MyView.$(OBJEXT) Win1.$(OBJEXT) \
	FG_Application.$(OBJEXT) FG_Object.$(OBJEXT) \
	FG_Container.$(OBJEXT) FG_Window.$(OBJEXT) FG_Screen.$(OBJEXT) \
	FG_Widget.$(OBJEXT) FG_TextWidget.$(OBJEXT) FG_Group.$(OBJEXT) \
	FG_Bitmap.$(OBJEXT) FG_Button.$(OBJEXT) FG_Label.$(OBJEXT) \
	FG_Edit.$(OBJEXT) FG_CheckBox.$(OBJEXT) \
	FG_RadioButton.$(OBJEXT) FG_TimerManager.$(OBJEXT) \
	FG_KeyMap.$(OBJEXT) FG_MsgMap.$(OBJEXT) FG_X11Adaptor.$(OBJEXT) \
	FG_X11DrawInterface.$(OBJEXT) FG_OSAdaptor.$(OBJEXT) \
	FG_String.$(OBJEXT) FG_Rect.$(OBJEXT)
FishGUI_OBJECTS = $(am_FishGUI_OBJECTS)
FishGUI_LDADD = $(LDADD)
FishGUI_DEPENDENCIES =
FishGUI_LDFLAGS =

DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"FishGUI\" -DVERSION=\"1.0\" -DHAVE_LIBX11=1 -DHAVE_LIBX11=1 -DHAVE_LIBXPM=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_X11_KEYSYM_H=1 -DHAVE_X11_XLIB_H=1 -DHAVE_X11_XUTIL_H=1 -DHAVE_X11_XUTIL_H=1 -DHAVE_X11_XPM_H=1 -DTIME_WITH_SYS_TIME=1 
DEFAULT_INCLUDES =  -I. -I$(srcdir)
CPPFLAGS = -I/GNU/2002/include
LDFLAGS = 
LIBS = -lXpm -lX11   -L/usr/openwin/lib -R/usr/openwin/lib
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/FG_Application.Po \
	$(DEPDIR)/FG_Bitmap.Po $(DEPDIR)/FG_Button.Po \
	$(DEPDIR)/FG_CheckBox.Po $(DEPDIR)/FG_Container.Po \
	$(DEPDIR)/FG_Edit.Po $(DEPDIR)/FG_Group.Po \
	$(DEPDIR)/FG_KeyMap.Po $(DEPDIR)/FG_Label.Po \
	$(DEPDIR)/FG_MsgMap.Po $(DEPDIR)/FG_OSAdaptor.Po \
	$(DEPDIR)/FG_Object.Po $(DEPDIR)/FG_RadioButton.Po \
	$(DEPDIR)/FG_Rect.Po $(DEPDIR)/FG_Screen.Po \
	$(DEPDIR)/FG_String.Po $(DEPDIR)/FG_TextWidget.Po \
	$(DEPDIR)/FG_TimerManager.Po $(DEPDIR)/FG_Widget.Po \
	$(DEPDIR)/FG_Window.Po $(DEPDIR)/FG_X11Adaptor.Po \
	$(DEPDIR)/FG_X11DrawInterface.Po \
	$(DEPDIR)/MainWindow.Po $(DEPDIR)/MyApp.Po \
	$(DEPDIR)/MyModel.Po $(DEPDIR)/MyView.Po \
	$(DEPDIR)/Win1.Po $(DEPDIR)/main.Po
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
CXXFLAGS = -g -O2
DIST_SOURCES = $(FishGUI_SOURCES)
DIST_COMMON = Makefile.am Makefile.in aclocal.m4 configure configure.in \
	depcomp install-sh missing mkinstalldirs
SOURCES = $(FishGUI_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$@ $(SHELL) ./config.status

$(top_builddir)/config.status: $(srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck
$(srcdir)/configure:  $(srcdir)/configure.in $(ACLOCAL_M4) $(CONFIGURE_DEPENDENCIES)
	cd $(srcdir) && $(AUTOCONF)

$(ACLOCAL_M4):  configure.in 
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo $$p1|sed '$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
main.$(OBJEXT): ../Source/OSStartup/main.cpp
MyApp.$(OBJEXT): ../Source/MVC_Application/MyApp.cpp
MainWindow.$(OBJEXT): ../Source/MVC_Application/MainWindow.cpp
MyModel.$(OBJEXT): ../Source/MVC_Application/MyModel.cpp
MyView.$(OBJEXT): ../Source/MVC_Application/MyView.cpp
Win1.$(OBJEXT): ../Source/MVC_Application/Win1.cpp
FG_Application.$(OBJEXT): ../Source/Framework/FG_Application.cpp
FG_Object.$(OBJEXT): ../Source/Framework/FG_Object.cpp
FG_Container.$(OBJEXT): ../Source/Framework/FG_Container.cpp
FG_Window.$(OBJEXT): ../Source/Framework/FG_Window.cpp
FG_Screen.$(OBJEXT): ../Source/Framework/FG_Screen.cpp
FG_Widget.$(OBJEXT): ../Source/Framework/FG_Widget.cpp
FG_TextWidget.$(OBJEXT): ../Source/Framework/FG_TextWidget.cpp
FG_Group.$(OBJEXT): ../Source/Framework/FG_Group.cpp
FG_Bitmap.$(OBJEXT): ../Source/Framework/FG_Bitmap.cpp
FG_Button.$(OBJEXT): ../Source/Framework/FG_Button.cpp
FG_Label.$(OBJEXT): ../Source/Framework/FG_Label.cpp
FG_Edit.$(OBJEXT): ../Source/Framework/FG_Edit.cpp
FG_CheckBox.$(OBJEXT): ../Source/Framework/FG_CheckBox.cpp
FG_RadioButton.$(OBJEXT): ../Source/Framework/FG_RadioButton.cpp
FG_TimerManager.$(OBJEXT): ../Source/Framework/FG_TimerManager.cpp
FG_KeyMap.$(OBJEXT): ../Source/Framework/FG_KeyMap.cpp
FG_MsgMap.$(OBJEXT): ../Source/Framework/FG_MsgMap.cpp
FG_X11Adaptor.$(OBJEXT): ../Source/OSAdaptor/FG_X11Adaptor.cpp
FG_X11DrawInterface.$(OBJEXT): \
	../Source/OSAdaptor/FG_X11DrawInterface.cpp
FG_OSAdaptor.$(OBJEXT): ../Source/OSAdaptor/FG_OSAdaptor.cpp
FG_String.$(OBJEXT): ../Source/Utility/FG_String.cpp
FG_Rect.$(OBJEXT): ../Source/Utility/FG_Rect.cpp
FishGUI$(EXEEXT): $(FishGUI_OBJECTS) $(FishGUI_DEPENDENCIES) 
	@rm -f FishGUI$(EXEEXT)
	$(CXXLINK) $(FishGUI_LDFLAGS) $(FishGUI_OBJECTS) $(FishGUI_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/FG_Application.Po
include $(DEPDIR)/FG_Bitmap.Po
include $(DEPDIR)/FG_Button.Po
include $(DEPDIR)/FG_CheckBox.Po
include $(DEPDIR)/FG_Container.Po
include $(DEPDIR)/FG_Edit.Po
include $(DEPDIR)/FG_Group.Po
include $(DEPDIR)/FG_KeyMap.Po
include $(DEPDIR)/FG_Label.Po
include $(DEPDIR)/FG_MsgMap.Po
include $(DEPDIR)/FG_OSAdaptor.Po
include $(DEPDIR)/FG_Object.Po
include $(DEPDIR)/FG_RadioButton.Po
include $(DEPDIR)/FG_Rect.Po
include $(DEPDIR)/FG_Screen.Po
include $(DEPDIR)/FG_String.Po
include $(DEPDIR)/FG_TextWidget.Po
include $(DEPDIR)/FG_TimerManager.Po
include $(DEPDIR)/FG_Widget.Po
include $(DEPDIR)/FG_Window.Po
include $(DEPDIR)/FG_X11Adaptor.Po
include $(DEPDIR)/FG_X11DrawInterface.Po
include $(DEPDIR)/MainWindow.Po
include $(DEPDIR)/MyApp.Po
include $(DEPDIR)/MyModel.Po
include $(DEPDIR)/MyView.Po
include $(DEPDIR)/Win1.Po
include $(DEPDIR)/main.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.cpp.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cpp.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

main.o: ../Source/OSStartup/main.cpp
	source='../Source/OSStartup/main.cpp' object='main.o' libtool=no \
	depfile='$(DEPDIR)/main.Po' tmpdepfile='$(DEPDIR)/main.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.o `test -f ../Source/OSStartup/main.cpp || echo '$(srcdir)/'`../Source/OSStartup/main.cpp

main.obj: ../Source/OSStartup/main.cpp
	source='../Source/OSStartup/main.cpp' object='main.obj' libtool=no \
	depfile='$(DEPDIR)/main.Po' tmpdepfile='$(DEPDIR)/main.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.obj `cygpath -w ../Source/OSStartup/main.cpp`

MyApp.o: ../Source/MVC_Application/MyApp.cpp
	source='../Source/MVC_Application/MyApp.cpp' object='MyApp.o' libtool=no \
	depfile='$(DEPDIR)/MyApp.Po' tmpdepfile='$(DEPDIR)/MyApp.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MyApp.o `test -f ../Source/MVC_Application/MyApp.cpp || echo '$(srcdir)/'`../Source/MVC_Application/MyApp.cpp

MyApp.obj: ../Source/MVC_Application/MyApp.cpp
	source='../Source/MVC_Application/MyApp.cpp' object='MyApp.obj' libtool=no \
	depfile='$(DEPDIR)/MyApp.Po' tmpdepfile='$(DEPDIR)/MyApp.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MyApp.obj `cygpath -w ../Source/MVC_Application/MyApp.cpp`

MainWindow.o: ../Source/MVC_Application/MainWindow.cpp
	source='../Source/MVC_Application/MainWindow.cpp' object='MainWindow.o' libtool=no \
	depfile='$(DEPDIR)/MainWindow.Po' tmpdepfile='$(DEPDIR)/MainWindow.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MainWindow.o `test -f ../Source/MVC_Application/MainWindow.cpp || echo '$(srcdir)/'`../Source/MVC_Application/MainWindow.cpp

MainWindow.obj: ../Source/MVC_Application/MainWindow.cpp
	source='../Source/MVC_Application/MainWindow.cpp' object='MainWindow.obj' libtool=no \
	depfile='$(DEPDIR)/MainWindow.Po' tmpdepfile='$(DEPDIR)/MainWindow.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MainWindow.obj `cygpath -w ../Source/MVC_Application/MainWindow.cpp`

MyModel.o: ../Source/MVC_Application/MyModel.cpp
	source='../Source/MVC_Application/MyModel.cpp' object='MyModel.o' libtool=no \
	depfile='$(DEPDIR)/MyModel.Po' tmpdepfile='$(DEPDIR)/MyModel.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MyModel.o `test -f ../Source/MVC_Application/MyModel.cpp || echo '$(srcdir)/'`../Source/MVC_Application/MyModel.cpp

MyModel.obj: ../Source/MVC_Application/MyModel.cpp
	source='../Source/MVC_Application/MyModel.cpp' object='MyModel.obj' libtool=no \
	depfile='$(DEPDIR)/MyModel.Po' tmpdepfile='$(DEPDIR)/MyModel.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MyModel.obj `cygpath -w ../Source/MVC_Application/MyModel.cpp`

MyView.o: ../Source/MVC_Application/MyView.cpp
	source='../Source/MVC_Application/MyView.cpp' object='MyView.o' libtool=no \
	depfile='$(DEPDIR)/MyView.Po' tmpdepfile='$(DEPDIR)/MyView.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MyView.o `test -f ../Source/MVC_Application/MyView.cpp || echo '$(srcdir)/'`../Source/MVC_Application/MyView.cpp

MyView.obj: ../Source/MVC_Application/MyView.cpp
	source='../Source/MVC_Application/MyView.cpp' object='MyView.obj' libtool=no \
	depfile='$(DEPDIR)/MyView.Po' tmpdepfile='$(DEPDIR)/MyView.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MyView.obj `cygpath -w ../Source/MVC_Application/MyView.cpp`

Win1.o: ../Source/MVC_Application/Win1.cpp
	source='../Source/MVC_Application/Win1.cpp' object='Win1.o' libtool=no \
	depfile='$(DEPDIR)/Win1.Po' tmpdepfile='$(DEPDIR)/Win1.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Win1.o `test -f ../Source/MVC_Application/Win1.cpp || echo '$(srcdir)/'`../Source/MVC_Application/Win1.cpp

Win1.obj: ../Source/MVC_Application/Win1.cpp
	source='../Source/MVC_Application/Win1.cpp' object='Win1.obj' libtool=no \
	depfile='$(DEPDIR)/Win1.Po' tmpdepfile='$(DEPDIR)/Win1.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Win1.obj `cygpath -w ../Source/MVC_Application/Win1.cpp`

FG_Application.o: ../Source/Framework/FG_Application.cpp
	source='../Source/Framework/FG_Application.cpp' object='FG_Application.o' libtool=no \
	depfile='$(DEPDIR)/FG_Application.Po' tmpdepfile='$(DEPDIR)/FG_Application.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Application.o `test -f ../Source/Framework/FG_Application.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Application.cpp

FG_Application.obj: ../Source/Framework/FG_Application.cpp
	source='../Source/Framework/FG_Application.cpp' object='FG_Application.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Application.Po' tmpdepfile='$(DEPDIR)/FG_Application.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Application.obj `cygpath -w ../Source/Framework/FG_Application.cpp`

FG_Object.o: ../Source/Framework/FG_Object.cpp
	source='../Source/Framework/FG_Object.cpp' object='FG_Object.o' libtool=no \
	depfile='$(DEPDIR)/FG_Object.Po' tmpdepfile='$(DEPDIR)/FG_Object.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Object.o `test -f ../Source/Framework/FG_Object.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Object.cpp

FG_Object.obj: ../Source/Framework/FG_Object.cpp
	source='../Source/Framework/FG_Object.cpp' object='FG_Object.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Object.Po' tmpdepfile='$(DEPDIR)/FG_Object.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Object.obj `cygpath -w ../Source/Framework/FG_Object.cpp`

FG_Container.o: ../Source/Framework/FG_Container.cpp
	source='../Source/Framework/FG_Container.cpp' object='FG_Container.o' libtool=no \
	depfile='$(DEPDIR)/FG_Container.Po' tmpdepfile='$(DEPDIR)/FG_Container.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Container.o `test -f ../Source/Framework/FG_Container.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Container.cpp

FG_Container.obj: ../Source/Framework/FG_Container.cpp
	source='../Source/Framework/FG_Container.cpp' object='FG_Container.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Container.Po' tmpdepfile='$(DEPDIR)/FG_Container.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Container.obj `cygpath -w ../Source/Framework/FG_Container.cpp`

FG_Window.o: ../Source/Framework/FG_Window.cpp
	source='../Source/Framework/FG_Window.cpp' object='FG_Window.o' libtool=no \
	depfile='$(DEPDIR)/FG_Window.Po' tmpdepfile='$(DEPDIR)/FG_Window.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Window.o `test -f ../Source/Framework/FG_Window.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Window.cpp

FG_Window.obj: ../Source/Framework/FG_Window.cpp
	source='../Source/Framework/FG_Window.cpp' object='FG_Window.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Window.Po' tmpdepfile='$(DEPDIR)/FG_Window.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Window.obj `cygpath -w ../Source/Framework/FG_Window.cpp`

FG_Screen.o: ../Source/Framework/FG_Screen.cpp
	source='../Source/Framework/FG_Screen.cpp' object='FG_Screen.o' libtool=no \
	depfile='$(DEPDIR)/FG_Screen.Po' tmpdepfile='$(DEPDIR)/FG_Screen.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Screen.o `test -f ../Source/Framework/FG_Screen.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Screen.cpp

FG_Screen.obj: ../Source/Framework/FG_Screen.cpp
	source='../Source/Framework/FG_Screen.cpp' object='FG_Screen.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Screen.Po' tmpdepfile='$(DEPDIR)/FG_Screen.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Screen.obj `cygpath -w ../Source/Framework/FG_Screen.cpp`

FG_Widget.o: ../Source/Framework/FG_Widget.cpp
	source='../Source/Framework/FG_Widget.cpp' object='FG_Widget.o' libtool=no \
	depfile='$(DEPDIR)/FG_Widget.Po' tmpdepfile='$(DEPDIR)/FG_Widget.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Widget.o `test -f ../Source/Framework/FG_Widget.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Widget.cpp

FG_Widget.obj: ../Source/Framework/FG_Widget.cpp
	source='../Source/Framework/FG_Widget.cpp' object='FG_Widget.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Widget.Po' tmpdepfile='$(DEPDIR)/FG_Widget.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Widget.obj `cygpath -w ../Source/Framework/FG_Widget.cpp`

FG_TextWidget.o: ../Source/Framework/FG_TextWidget.cpp
	source='../Source/Framework/FG_TextWidget.cpp' object='FG_TextWidget.o' libtool=no \
	depfile='$(DEPDIR)/FG_TextWidget.Po' tmpdepfile='$(DEPDIR)/FG_TextWidget.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_TextWidget.o `test -f ../Source/Framework/FG_TextWidget.cpp || echo '$(srcdir)/'`../Source/Framework/FG_TextWidget.cpp

FG_TextWidget.obj: ../Source/Framework/FG_TextWidget.cpp
	source='../Source/Framework/FG_TextWidget.cpp' object='FG_TextWidget.obj' libtool=no \
	depfile='$(DEPDIR)/FG_TextWidget.Po' tmpdepfile='$(DEPDIR)/FG_TextWidget.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_TextWidget.obj `cygpath -w ../Source/Framework/FG_TextWidget.cpp`

FG_Group.o: ../Source/Framework/FG_Group.cpp
	source='../Source/Framework/FG_Group.cpp' object='FG_Group.o' libtool=no \
	depfile='$(DEPDIR)/FG_Group.Po' tmpdepfile='$(DEPDIR)/FG_Group.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Group.o `test -f ../Source/Framework/FG_Group.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Group.cpp

FG_Group.obj: ../Source/Framework/FG_Group.cpp
	source='../Source/Framework/FG_Group.cpp' object='FG_Group.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Group.Po' tmpdepfile='$(DEPDIR)/FG_Group.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Group.obj `cygpath -w ../Source/Framework/FG_Group.cpp`

FG_Bitmap.o: ../Source/Framework/FG_Bitmap.cpp
	source='../Source/Framework/FG_Bitmap.cpp' object='FG_Bitmap.o' libtool=no \
	depfile='$(DEPDIR)/FG_Bitmap.Po' tmpdepfile='$(DEPDIR)/FG_Bitmap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Bitmap.o `test -f ../Source/Framework/FG_Bitmap.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Bitmap.cpp

FG_Bitmap.obj: ../Source/Framework/FG_Bitmap.cpp
	source='../Source/Framework/FG_Bitmap.cpp' object='FG_Bitmap.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Bitmap.Po' tmpdepfile='$(DEPDIR)/FG_Bitmap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Bitmap.obj `cygpath -w ../Source/Framework/FG_Bitmap.cpp`

FG_Button.o: ../Source/Framework/FG_Button.cpp
	source='../Source/Framework/FG_Button.cpp' object='FG_Button.o' libtool=no \
	depfile='$(DEPDIR)/FG_Button.Po' tmpdepfile='$(DEPDIR)/FG_Button.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Button.o `test -f ../Source/Framework/FG_Button.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Button.cpp

FG_Button.obj: ../Source/Framework/FG_Button.cpp
	source='../Source/Framework/FG_Button.cpp' object='FG_Button.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Button.Po' tmpdepfile='$(DEPDIR)/FG_Button.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Button.obj `cygpath -w ../Source/Framework/FG_Button.cpp`

FG_Label.o: ../Source/Framework/FG_Label.cpp
	source='../Source/Framework/FG_Label.cpp' object='FG_Label.o' libtool=no \
	depfile='$(DEPDIR)/FG_Label.Po' tmpdepfile='$(DEPDIR)/FG_Label.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Label.o `test -f ../Source/Framework/FG_Label.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Label.cpp

FG_Label.obj: ../Source/Framework/FG_Label.cpp
	source='../Source/Framework/FG_Label.cpp' object='FG_Label.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Label.Po' tmpdepfile='$(DEPDIR)/FG_Label.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Label.obj `cygpath -w ../Source/Framework/FG_Label.cpp`

FG_Edit.o: ../Source/Framework/FG_Edit.cpp
	source='../Source/Framework/FG_Edit.cpp' object='FG_Edit.o' libtool=no \
	depfile='$(DEPDIR)/FG_Edit.Po' tmpdepfile='$(DEPDIR)/FG_Edit.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Edit.o `test -f ../Source/Framework/FG_Edit.cpp || echo '$(srcdir)/'`../Source/Framework/FG_Edit.cpp

FG_Edit.obj: ../Source/Framework/FG_Edit.cpp
	source='../Source/Framework/FG_Edit.cpp' object='FG_Edit.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Edit.Po' tmpdepfile='$(DEPDIR)/FG_Edit.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Edit.obj `cygpath -w ../Source/Framework/FG_Edit.cpp`

FG_CheckBox.o: ../Source/Framework/FG_CheckBox.cpp
	source='../Source/Framework/FG_CheckBox.cpp' object='FG_CheckBox.o' libtool=no \
	depfile='$(DEPDIR)/FG_CheckBox.Po' tmpdepfile='$(DEPDIR)/FG_CheckBox.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_CheckBox.o `test -f ../Source/Framework/FG_CheckBox.cpp || echo '$(srcdir)/'`../Source/Framework/FG_CheckBox.cpp

FG_CheckBox.obj: ../Source/Framework/FG_CheckBox.cpp
	source='../Source/Framework/FG_CheckBox.cpp' object='FG_CheckBox.obj' libtool=no \
	depfile='$(DEPDIR)/FG_CheckBox.Po' tmpdepfile='$(DEPDIR)/FG_CheckBox.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_CheckBox.obj `cygpath -w ../Source/Framework/FG_CheckBox.cpp`

FG_RadioButton.o: ../Source/Framework/FG_RadioButton.cpp
	source='../Source/Framework/FG_RadioButton.cpp' object='FG_RadioButton.o' libtool=no \
	depfile='$(DEPDIR)/FG_RadioButton.Po' tmpdepfile='$(DEPDIR)/FG_RadioButton.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_RadioButton.o `test -f ../Source/Framework/FG_RadioButton.cpp || echo '$(srcdir)/'`../Source/Framework/FG_RadioButton.cpp

FG_RadioButton.obj: ../Source/Framework/FG_RadioButton.cpp
	source='../Source/Framework/FG_RadioButton.cpp' object='FG_RadioButton.obj' libtool=no \
	depfile='$(DEPDIR)/FG_RadioButton.Po' tmpdepfile='$(DEPDIR)/FG_RadioButton.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_RadioButton.obj `cygpath -w ../Source/Framework/FG_RadioButton.cpp`

FG_TimerManager.o: ../Source/Framework/FG_TimerManager.cpp
	source='../Source/Framework/FG_TimerManager.cpp' object='FG_TimerManager.o' libtool=no \
	depfile='$(DEPDIR)/FG_TimerManager.Po' tmpdepfile='$(DEPDIR)/FG_TimerManager.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_TimerManager.o `test -f ../Source/Framework/FG_TimerManager.cpp || echo '$(srcdir)/'`../Source/Framework/FG_TimerManager.cpp

FG_TimerManager.obj: ../Source/Framework/FG_TimerManager.cpp
	source='../Source/Framework/FG_TimerManager.cpp' object='FG_TimerManager.obj' libtool=no \
	depfile='$(DEPDIR)/FG_TimerManager.Po' tmpdepfile='$(DEPDIR)/FG_TimerManager.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_TimerManager.obj `cygpath -w ../Source/Framework/FG_TimerManager.cpp`

FG_KeyMap.o: ../Source/Framework/FG_KeyMap.cpp
	source='../Source/Framework/FG_KeyMap.cpp' object='FG_KeyMap.o' libtool=no \
	depfile='$(DEPDIR)/FG_KeyMap.Po' tmpdepfile='$(DEPDIR)/FG_KeyMap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_KeyMap.o `test -f ../Source/Framework/FG_KeyMap.cpp || echo '$(srcdir)/'`../Source/Framework/FG_KeyMap.cpp

FG_KeyMap.obj: ../Source/Framework/FG_KeyMap.cpp
	source='../Source/Framework/FG_KeyMap.cpp' object='FG_KeyMap.obj' libtool=no \
	depfile='$(DEPDIR)/FG_KeyMap.Po' tmpdepfile='$(DEPDIR)/FG_KeyMap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_KeyMap.obj `cygpath -w ../Source/Framework/FG_KeyMap.cpp`

FG_MsgMap.o: ../Source/Framework/FG_MsgMap.cpp
	source='../Source/Framework/FG_MsgMap.cpp' object='FG_MsgMap.o' libtool=no \
	depfile='$(DEPDIR)/FG_MsgMap.Po' tmpdepfile='$(DEPDIR)/FG_MsgMap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_MsgMap.o `test -f ../Source/Framework/FG_MsgMap.cpp || echo '$(srcdir)/'`../Source/Framework/FG_MsgMap.cpp

FG_MsgMap.obj: ../Source/Framework/FG_MsgMap.cpp
	source='../Source/Framework/FG_MsgMap.cpp' object='FG_MsgMap.obj' libtool=no \
	depfile='$(DEPDIR)/FG_MsgMap.Po' tmpdepfile='$(DEPDIR)/FG_MsgMap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_MsgMap.obj `cygpath -w ../Source/Framework/FG_MsgMap.cpp`

FG_X11Adaptor.o: ../Source/OSAdaptor/FG_X11Adaptor.cpp
	source='../Source/OSAdaptor/FG_X11Adaptor.cpp' object='FG_X11Adaptor.o' libtool=no \
	depfile='$(DEPDIR)/FG_X11Adaptor.Po' tmpdepfile='$(DEPDIR)/FG_X11Adaptor.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_X11Adaptor.o `test -f ../Source/OSAdaptor/FG_X11Adaptor.cpp || echo '$(srcdir)/'`../Source/OSAdaptor/FG_X11Adaptor.cpp

FG_X11Adaptor.obj: ../Source/OSAdaptor/FG_X11Adaptor.cpp
	source='../Source/OSAdaptor/FG_X11Adaptor.cpp' object='FG_X11Adaptor.obj' libtool=no \
	depfile='$(DEPDIR)/FG_X11Adaptor.Po' tmpdepfile='$(DEPDIR)/FG_X11Adaptor.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_X11Adaptor.obj `cygpath -w ../Source/OSAdaptor/FG_X11Adaptor.cpp`

FG_X11DrawInterface.o: ../Source/OSAdaptor/FG_X11DrawInterface.cpp
	source='../Source/OSAdaptor/FG_X11DrawInterface.cpp' object='FG_X11DrawInterface.o' libtool=no \
	depfile='$(DEPDIR)/FG_X11DrawInterface.Po' tmpdepfile='$(DEPDIR)/FG_X11DrawInterface.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_X11DrawInterface.o `test -f ../Source/OSAdaptor/FG_X11DrawInterface.cpp || echo '$(srcdir)/'`../Source/OSAdaptor/FG_X11DrawInterface.cpp

FG_X11DrawInterface.obj: ../Source/OSAdaptor/FG_X11DrawInterface.cpp
	source='../Source/OSAdaptor/FG_X11DrawInterface.cpp' object='FG_X11DrawInterface.obj' libtool=no \
	depfile='$(DEPDIR)/FG_X11DrawInterface.Po' tmpdepfile='$(DEPDIR)/FG_X11DrawInterface.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_X11DrawInterface.obj `cygpath -w ../Source/OSAdaptor/FG_X11DrawInterface.cpp`

FG_OSAdaptor.o: ../Source/OSAdaptor/FG_OSAdaptor.cpp
	source='../Source/OSAdaptor/FG_OSAdaptor.cpp' object='FG_OSAdaptor.o' libtool=no \
	depfile='$(DEPDIR)/FG_OSAdaptor.Po' tmpdepfile='$(DEPDIR)/FG_OSAdaptor.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_OSAdaptor.o `test -f ../Source/OSAdaptor/FG_OSAdaptor.cpp || echo '$(srcdir)/'`../Source/OSAdaptor/FG_OSAdaptor.cpp

FG_OSAdaptor.obj: ../Source/OSAdaptor/FG_OSAdaptor.cpp
	source='../Source/OSAdaptor/FG_OSAdaptor.cpp' object='FG_OSAdaptor.obj' libtool=no \
	depfile='$(DEPDIR)/FG_OSAdaptor.Po' tmpdepfile='$(DEPDIR)/FG_OSAdaptor.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_OSAdaptor.obj `cygpath -w ../Source/OSAdaptor/FG_OSAdaptor.cpp`

FG_String.o: ../Source/Utility/FG_String.cpp
	source='../Source/Utility/FG_String.cpp' object='FG_String.o' libtool=no \
	depfile='$(DEPDIR)/FG_String.Po' tmpdepfile='$(DEPDIR)/FG_String.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_String.o `test -f ../Source/Utility/FG_String.cpp || echo '$(srcdir)/'`../Source/Utility/FG_String.cpp

FG_String.obj: ../Source/Utility/FG_String.cpp
	source='../Source/Utility/FG_String.cpp' object='FG_String.obj' libtool=no \
	depfile='$(DEPDIR)/FG_String.Po' tmpdepfile='$(DEPDIR)/FG_String.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_String.obj `cygpath -w ../Source/Utility/FG_String.cpp`

FG_Rect.o: ../Source/Utility/FG_Rect.cpp
	source='../Source/Utility/FG_Rect.cpp' object='FG_Rect.o' libtool=no \
	depfile='$(DEPDIR)/FG_Rect.Po' tmpdepfile='$(DEPDIR)/FG_Rect.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Rect.o `test -f ../Source/Utility/FG_Rect.cpp || echo '$(srcdir)/'`../Source/Utility/FG_Rect.cpp

FG_Rect.obj: ../Source/Utility/FG_Rect.cpp
	source='../Source/Utility/FG_Rect.cpp' object='FG_Rect.obj' libtool=no \
	depfile='$(DEPDIR)/FG_Rect.Po' tmpdepfile='$(DEPDIR)/FG_Rect.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FG_Rect.obj `cygpath -w ../Source/Utility/FG_Rect.cpp`
CXXDEPMODE = depmode=gcc
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = .
# Avoid unsightly `./'.
distdir = $(PACKAGE)-$(VERSION)

GZIP_ENV = --best

distdir: $(DISTFILES)
	-chmod -R a+w $(distdir) >/dev/null 2>&1; rm -rf $(distdir)
	mkdir $(distdir)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	-chmod -R a+w $(distdir) >/dev/null 2>&1; rm -rf $(distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	-chmod -R a+w $(distdir) > /dev/null 2>&1; rm -rf $(distdir)
	GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(AMTAR) xf -
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/=build
	mkdir $(distdir)/=inst
	chmod a-w $(distdir)
	dc_install_base=`CDPATH=: && cd $(distdir)/=inst && pwd` \
	  && cd $(distdir)/=build \
	  && ../configure --srcdir=.. --prefix=$$dc_install_base \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && (test `find $$dc_install_base -type f -print | wc -l` -le 1 \
	     || (echo "Error: files left after uninstall" 1>&2; \
	         exit 1) ) \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && $(MAKE) $(AM_MAKEFLAGS) distclean \
	  && rm -f $(distdir).tar.gz \
	  && (test `find . -type f -print | wc -l` -eq 0 \
	     || (echo "Error: files left after distclean" 1>&2; \
	         exit 1) )
	-chmod -R a+w $(distdir) > /dev/null 2>&1; rm -rf $(distdir)
	@echo "$(distdir).tar.gz is ready for distribution" | \
	  sed 'h;s/./=/g;p;x;p;x'
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

dist-all: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	-chmod -R a+w $(distdir) >/dev/null 2>&1; rm -rf $(distdir)
distclean: distclean-am
	-rm -f config.status config.cache config.log
distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic dist dist-all distcheck distclean \
	distclean-compile distclean-depend distclean-generic \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-binPROGRAMS install-data install-data-am \
	install-exec install-exec-am install-info install-info-am \
	install-man install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic tags \
	uninstall uninstall-am uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
